# Generated by Django 4.0.5 on 2022-06-02 05:57

import APP.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(default=APP.models.createHash, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
                ('dateTime', models.DateTimeField(default=datetime.datetime(2022, 6, 2, 11, 27, 8, 204882))),
            ],
        ),
    ]
