# Generated by Django 4.0.5 on 2022-06-03 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_note_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 15, 58, 9, 268471)),
        ),
    ]
