# Generated by Django 4.0.5 on 2022-06-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_alter_note_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateTime',
            field=models.CharField(default='2022-06-05 10:47:51.241240', max_length=30),
        ),
    ]
